servers = false
security = true
tags = true
externalDocs = false

[x-openapi-filter.logger]
level = "debug"

[x-openapi-filter.loader]
external_refs_allowed = false

[paths]
"/api/example" = [ "get", "post" ]
"/api/some-another-example" = [ "put" ]

[components]
securitySchemes = [ "ApiKeyAuth" ]
