x-openapi-filter:
  logger:
    level: debug
  loader:
    external_refs_allowed: false

servers: false

paths:
  /api/example:
    - post

components:
  securitySchemes:
    - ApiKeyAuth

security: true
tags: true
externalDocs: false
