x-openapi-filter:
  logger:
    level: debug
  loader:
    external_refs_allowed: false

servers: false
security: true
tags: true
externalDocs: false

paths:
  /api/example:
    - get
    - post
  /api/some-another:
    - put

components:
  securitySchemes:
    - ApiKeyAuth
