x-openapi-filter:
  logger:
    level: debug

servers: true
security: true
tags: true
externalDocs: true

paths:
  /pet: [ post, put ]
  /pet/{petId}/uploadImage: [ post ]
  /user/login: [ get ]

components:
  securitySchemes:
    - petstore_auth
